baseURL = "https://blog.tnt.pub"
languageCode = "en-us"
title = "打孔纸带"
theme = "echo"
DefaultContentLanguage = "cn"
# 自动检测是否包含中文/日文/韩文，该参数会影响摘要和字数统计功能，建议设置为true
hasCJKLanguage = true
# 设置页面生成形式，将默认的网站路径/修改成.html
uglyURLs = true
googleAnalytics = ""      # UA-XXXXXXXX-X

## 评论系统
changyanAppid = "" # Changyan app id             # 畅言
changyanAppkey = "" # Changyan app key
disqusShortname = "dongdongbo's blog" # disqus account name
livereUID = "" # LiveRe UID                  # 来必力

[markup.highlight]
codeFences = true # 高亮markdown的代码块
guessSyntax = true # 高亮markdown中没有标注语言的代码块
hl_Lines = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = true
style = "manni"
tabWidth = 2

# https://gohugo.io/content-management/urls/#aliases
[permalinks]
posts = "/:filename"

[outputFormats.RSS]
mediatype = "application/rss"
baseName = "atom"

[services.rss]
limit = 20

[author]
name = "ge"
avatar = "https://gitee.com/XiuYuGe/resource/raw/master/2021/04/touming.png"
bio = "to be continue..."
homepage = "https://blog.tnt.pub/"

[params]
favicon = "https://gitee.com/XiuYuGe/resource/raw/master/2021/04/touming.png"
keywords = "打孔纸带"
description = "打孔纸带"
toc = true
navItems = [
  ["首页", "/"],
  ["归档", "/posts.html"],
  ["关于", "/about.html"],
  ["RSS", "/atom.xml"]
]
# rss 全文输出
rssFullContent = true
uglyURLs = true
busuanzi = true # 是否使用不蒜子统计站点访问量
staticCDNPrefix = "https://cdn.bootcss.com/font-awesome/5.11.2"
extraHead = '<script async src="https://www.googletagmanager.com/gtag/js?id=UA-xxx"></script>'
postAds = ""
profileAds = '<div class="bg-white shadow"><a href="https://curl.qcloud.com/hFIbbPnZ"><img class="object-cover w-auto mx-auto mt-6" src="https://gitee.com/huangxd/imges/raw/master/小书匠/1607005821458.png" alt="【腾讯云】腾讯云服务器安全可靠高性能，多种配置供您选择"></a></div>'
notFoundAds = ''

# 开启版权声明，协议名字和链接都可以换
[params.cc]
name = "署名-非商业性使用 4.0 国际 (CC BY-NC 4.0)"
link = "https://creativecommons.org/licenses/by-nc/4.0/deed.zh"

# 文章打赏
[params.reward]
enable = true
title = "打赏"
wechat = "https://gitee.com/XiuYuGe/resource/raw/master/2021/04/wechat.png" # 微信二维码
alipay = "https://gitee.com/XiuYuGe/resource/raw/master/2021/04/ali.png" # 支付宝二维码

############## 评论系统  start ##############
[params.gitment] # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
owner = "" # Your GitHub ID
repo = "" # The repo to store comments
clientId = "" # Your client ID
clientSecret = "" # Your client secret

[params.utterances] # https://utteranc.es/
owner = "GeXyu" # Your GitHub ID
repo = "hugo-comment" # The repo to store comments

[params.gitalk] # Gitalk is a comment system based on GitHub issues. see https://github.com/gitalk/gitalk
owner = "" # Your GitHub ID
repo = "" # The repo to store comments
clientId = "" # Your client ID
clientSecret = "" # Your client secret

# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
enable = false
appId = '你的appId'
appKey = '你的appKey'
notify = false # mail notifier , https://github.com/xCss/Valine/wiki
verify = false # Verification code
avatar = 'mm'
placeholder = '说点什么吧...'
visitor = false

############ 评论系统  end ##############
## 社交链接
[social]
github = "GeXyu"
#jsfiddle = "forecho"
#codepen = "forecho"
#dribbble = "forecho"
#behance = "forecho"
#flickr = "forecho"
#instagram = "forecho"
#youtube = "forecho"
#vimeo = "forecho"
#vine = "forecho"
#medium = "forecho"
#wordpress = "forecho"
#tumblr = "forecho"
#linkedin = "forecho"
#slideshare = "forecho"
#stackoverflow = "forecho"
#reddit = "forecho"
#pinterest = "forecho"
#weibo = "forecho"
#facebook = "forecho"
#twitter = "caizhenghai"
#douban = "ipzone"
rss = "/atom.xml"
